package edu.neu.khoury.FitnessApp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.Query;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Logger;

@RestController
public class FitnessAppController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FitnessAppRepository fitnessAppRepository;


    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    private final Logger LOG = Logger.getLogger(this.getClass().getCanonicalName());

    @GetMapping("/fitness")
    public Iterable<Fitness> getAllActivities(){//@RequestParam(value = "id") int id){




        return fitnessAppRepository.findAll();
    }


    @GetMapping("/running")
    public Iterable<Fitness> AlActivities() {

        return fitnessAppRepository.findRunning();
    }


    @GetMapping("/helloWorld")
    public String helloWorld(){
        return "Hello World!";
    }

    @PostMapping("/add")
    public Fitness postGreeting(@RequestParam String activity,
                                @RequestParam int duration, @RequestParam int calories,
                                @RequestParam int distance, @RequestParam String date)
    {

        Fitness one = new Fitness();
        one.setActivity(activity);
        one.setDuration(duration);
        one.setCalories(calories);
        one.setDistance(distance);
        one.setDate(date);

        fitnessAppRepository.save(one);
        return one;
    }
}


